// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tawptzlxcoimqswpwvoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhd3B0emx4Y29pbXFzd3B3dm9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzQwOTMsImV4cCI6MjA3NDU1MDA5M30.ePePjYrZ5rzGAmeXZK8ay3q8tc4k2lWvykUcU0Ctc4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});